/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xEpFpa2OI2W
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Rubik } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import Link from "next/link"
import { Menubar, MenubarMenu, MenubarTrigger, MenubarContent, MenubarItem } from "@/components/ui/menubar"
import { Sheet, SheetContent } from "@/components/ui/sheet"
import { ModeToggle } from "./darkmode"

export function Navbar() {
  const [isOpen, setIsOpen] = useState(false)
  return (
    <header className="flex h-16 items-center justify-between px-4 md:px-6">
      <Link href="#" className="flex items-center gap-2 text-lg font-semibold" prefetch={false}>
        <MountainIcon className="h-6 w-6" />
        <span className="sr-only">Acme Inc</span>
      </Link>
      <div className="flex items-center">
        <button
          className="rounded-md p-2 transition-colors hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-400 dark:hover:bg-gray-800 md:hidden"
          onClick={() => setIsOpen(!isOpen)}
        >
          <VolumeXIcon className="h-6 w-6" />
          <span className="sr-only">Toggle navigation</span>
        </button>
        <Menubar className="hidden md:flex">
          <MenubarMenu>
            <MenubarTrigger>Home</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Main Page
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Features
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Pricing
                </Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
          <MenubarMenu>
            <MenubarTrigger>About</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Company
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Team
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Careers
                </Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
          <MenubarMenu>
            <MenubarTrigger>Services</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Overview
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Consulting
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Development
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Design
                </Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
          <MenubarMenu>
            <MenubarTrigger>Contact</MenubarTrigger>
            <MenubarContent>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Get in Touch
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Support
                </Link>
              </MenubarItem>
              <MenubarItem>
                <Link href="#" prefetch={false}>
                  Sales
                </Link>
              </MenubarItem>
            </MenubarContent>
          </MenubarMenu>
        </Menubar>
      </div>
      <ModeToggle/>
      <Sheet open={isOpen} onOpenChange={setIsOpen}>
        <SheetContent side="top" className="bg-white dark:bg-gray-950 md:hidden">
          <div className="flex flex-col gap-4 p-4">
            
            <Link href="#" className="font-semibold" prefetch={false}>
              Home
            </Link>
            <Link href="#" className="font-semibold" prefetch={false}>
              About
            </Link>
            <Link href="#" className="font-semibold" prefetch={false}>
              Services
            </Link>
            <Link href="#" className="font-semibold" prefetch={false}>
              Contact
            </Link>
          </div>
        </SheetContent>
      </Sheet>
    </header>
  )
}

function MenuIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  )
}


function MountainIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function VolumeXIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="11 5 6 9 2 9 2 15 6 15 11 19 11 5" />
      <line x1="22" x2="16" y1="9" y2="15" />
      <line x1="16" x2="22" y1="9" y2="15" />
    </svg>
  )
}
